##
## It does `docker-compose up -d` before starting the project, or else it gets
## the hose, again!
##
version: '2.1'
services:
  'rabbitmq':
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
      ## username: guest
      ## password: guest
  'db-alpha':
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes: 
      - db-alpha:/var/lib/postgresql/data
  'db-omega':
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5444:5432'
    volumes: 
      - db-omega:/var/lib/postgresql/data
  'minio':
    image: bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minminio
      - MINIO_ROOT_PASSWORD=minminio
volumes:
  db-alpha:
    driver: local
  db-omega:
    driver: local
